### ISSUE TITLE
Bug: The if condition will end up with java exception when return url string is null

### ISSUE THREAD

**Issue by gravitydevelopment** [gravitydevelopment/webtermites#5]
**Class file**: procs.java
**line no**: 86 - 89

**Bug description**:
The if condition for substring replacing doesn't cater the condition of the return url is null.

**Outcome**:
When return url is null, java exception will be thrown:

`Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1`
 `     at java.lang.String.substring(Unknown Source)`
`      at webtermites.procs.checkUrlAccessibility(procs.java:86)`
`      at webtermites.wfreadhtml.hrefTest(wfreadhtml.java:56)`
`      at webtermites.termites.termitesFlow(termites.java:48)`
`      at webtermites.init.main(init.java:61) `

**Comment by gravitydevelopment** [comment]
Fix at wfreadhtml.java, line: 56
